# Tahmine Dayalı Değer Atama Yöntemleri

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import missingno as msngo

df = sns.load_dataset("titanic")
df = df.select_dtypes(include=["float64","int64"])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [2]:
!pip install ycimpute

You should consider upgrading via the 'c:\users\alperen kavurga\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


# K en Yakın Komşu Algoritması

In [4]:
from ycimpute.imputer import knnimput

var_names = list(df)   # bu değişken isimlerine tekrar df yaparken ihtiyacım olcam

n_df = np.array (df)  # knn algoritması için df değil numpy array i lazım bana
n_df

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [5]:
n_df.shape

(891, 6)

In [6]:
dff= knnimput.KNN(k=4).complete(n_df)   #complete yani tamamla n_df teki boşlukları en yakın 4 komşuya göre tamamlar

Imputing row 1/891 with 0 missing, elapsed time: 0.698
Imputing row 101/891 with 0 missing, elapsed time: 0.708
Imputing row 201/891 with 0 missing, elapsed time: 0.711
Imputing row 301/891 with 1 missing, elapsed time: 0.718
Imputing row 401/891 with 0 missing, elapsed time: 0.724
Imputing row 501/891 with 0 missing, elapsed time: 0.726
Imputing row 601/891 with 0 missing, elapsed time: 0.735
Imputing row 701/891 with 0 missing, elapsed time: 0.742
Imputing row 801/891 with 0 missing, elapsed time: 0.747


In [12]:
type(dff)

numpy.ndarray

In [14]:
dff = pd.DataFrame(dff,columns=var_names)
dff.head()

survived  pclass   age  sibsp  parch     fare
0       0.0     3.0  22.0    1.0    0.0   7.2500
1       1.0     1.0  38.0    1.0    0.0  71.2833
2       1.0     3.0  26.0    0.0    0.0   7.9250
3       1.0     1.0  35.0    1.0    0.0  53.1000
4       0.0     3.0  35.0    0.0    0.0   8.0500

In [15]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

# Random Forest Algoritması

In [16]:
df = sns.load_dataset("titanic")
df = df.select_dtypes(include=["float64","int64"])
print(df.head())
df.isnull().sum()

var_names = list(df)   

n_df = np.array (df)  
n_df

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [24]:
from ycimpute.imputer import iterforest

dff = iterforest.IterImput().complete(n_df)

AttributeError: module 'ycimpute.imputer.iterforest' has no attribute 'IterImput'

# EM Algoritması

In [26]:
df = sns.load_dataset("titanic")
df = df.select_dtypes(include=["float64","int64"])
print(df.head())
df.isnull().sum()

var_names = list(df)   

n_df = np.array (df)  
n_df

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [28]:
from ycimpute.imputer import EM

dff = EM().complete(n_df)

In [29]:
dff = pd.DataFrame(dff,columns=var_names)
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64